# Generated by Django 3.0.7 on 2020-06-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff_regitser',
            new_name='staffs_regitser',
        ),
        migrations.RenameModel(
            old_name='student_regitser',
            new_name='students_regitser',
        ),
    ]
