# Generated by Django 3.0.7 on 2020-06-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200621_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staffs_regitser',
            new_name='staff_regitser',
        ),
    ]
