# Generated by Django 3.0.7 on 2020-06-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200621_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_regitser',
            name='idd',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='staff_regitser',
            name='psw',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students_regitser',
            name='idd',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='students_regitser',
            name='psw',
            field=models.CharField(max_length=20),
        ),
    ]
