# Generated by Django 3.0.7 on 2020-06-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200622_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='mail',
            new_name='idd',
        ),
    ]
