# Generated by Django 3.0.7 on 2020-06-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200622_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload',
            new_name='post',
        ),
    ]
