# Generated by Django 3.0.7 on 2020-06-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200622_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='upload',
        ),
    ]
